name: Continuous Deployment

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: docker pull developersiladi/nestjs-cicd:latest
      - name: Stop and remove the container
        run: docker stop nestjs-cicd && docker rm nestjs-cicd || true

      - name: Run the container
        run: docker run -d --name nestjs-cicd -p 3000:3000 developersiladi/nestjs-cicd:latest
